-- Ranking das culturas com maior produtividade
SELECT P.NOME, SUM(PA.VALOR) AS PRODUTIVIDADE_TOTAL
FROM PRODUCAO_AGRICOLA PA
JOIN PRODUTO_AGRICOLA P ON PA.PRODUTO_ID = P.ID
GROUP BY P.NOME
ORDER BY PRODUTIVIDADE_TOTAL DESC;

-- Produção total de uma determinada cultura
SELECT P.NOME, SUM(PA.VALOR) AS PRODUCAO_TOTAL
FROM PRODUCAO_AGRICOLA PA
JOIN PRODUTO_AGRICOLA P ON PA.PRODUTO_ID = P.ID
WHERE P.NOME = 'Soja'
GROUP BY P.NOME;

-- Produção total de todos os produtos agrícolas
SELECT P.NOME, SUM(PA.VALOR) AS PRODUCAO_TOTAL
FROM PRODUCAO_AGRICOLA PA
JOIN PRODUTO_AGRICOLA P ON PA.PRODUTO_ID = P.ID
GROUP BY P.NOME
ORDER BY PRODUCAO_TOTAL DESC;

-- Produção total de todos os produtos pecuários
SELECT P.NOME, SUM(PP.VALOR) AS PRODUCAO_TOTAL
FROM PRODUCAO_PECUARIA PP
JOIN PRODUTO_PECUARIO P ON PP.PRODUTO_ID = P.ID
GROUP BY P.NOME
ORDER BY PRODUCAO_TOTAL DESC;

-- Comparação da produção agrícola e pecuária
SELECT 'Agrícola' AS TIPO, SUM(PA.VALOR) AS PRODUCAO_TOTAL
FROM PRODUCAO_AGRICOLA PA
UNION ALL
SELECT 'Pecuária' AS TIPO, SUM(PP.VALOR) AS PRODUCAO_TOTAL
FROM PRODUCAO_PECUARIA PP;
